// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sufzhzdtdhewkqfnxupu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN1ZnpoemR0ZGhld2txZm54dXB1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0MzkyNDcsImV4cCI6MjA2NjAxNTI0N30.T8OqczGhooY1V-izDuPVcCptqZO_L2ORIqKUTGRoX-o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);